voltage = 3.3   # pretend we measured 3.3V on an input, supposed to be the pressure sensor
voltage = get_analog_in(0)
target_pose = pose_add(get_actual_tcp_pose(), p[0, 0, 0.5, 0, 0, 0]) #30 mm up
if (voltage > 2.0):
    set_digital_out(0, True)   #close gripper
    sleep(1.0)
    # lift the product
    movel(target_pose, a = 1.0, v = 0.25)
else:
    popup("Voltage too low - Gripper not activated")
end
