# Figured out the position with joints position rather than using the automated kinematics,
#even thought it doesn't conform with the preset standard (all automated kinematics except home / pickup area positions)
sleep(1)

on_target_position = [0, -1.918888889, -2.79253, 0, 1.5708, 0]
popup("Picking up first target", title = "Second pick", blocking = True)

pos = get_forward_kin(on_target_position)
movel(pos)

