def execute_gripping_action():

    popup("Gripper action commencing", title = "Gripper action", blocking = True)

    voltage = get_standard_analog_in(0)
    target_pose = pose_add(get_actual_tcp_pose(), p[0, 0, 0.1, 0, 0, 0]) #50 mm up
    if (voltage != 0):
        sleep(1.0)
        movel(target_pose)
        set_standard_digital_out(0, True)   #close gripper

    else:
        popup("Voltage too low - Gripper not activated - STOPPING", title = "FAILURE", blocking = True)
    end
end
