sleep(1)

popup("Gripper action commencing", title = "Gripper action", blocking = True)

voltage = get_standard_analog_in(0)
target_pose = pose_add(get_actual_tcp_pose(), p[0, 0, 0.5, 0, 0, 0]) #50 mm up
if (voltage > 2.0):
    set_standard_digital_out(0, True)   #close gripper
    sleep(1.0)
    # lift the product
    movel(target_pose)
else:
    popup("Voltage too low - Gripper not activated", title = "FAILURE", blocking = True )
end
